# Generated by Django 5.2.16 on 2026-07-28 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('url', models.URLField(max_length=600)),
                ('kind', models.CharField(choices=[('news_rss', 'Nachrichten (RSS)'), ('closure_csv', 'Verkehrsmeldungen (CSV)')], max_length=20)),
                ('locality', models.CharField(max_length=80)),
                ('attribution', models.CharField(max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HandoverEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('station', 'Wache'), ('vehicle', 'Fahrzeugstatus'), ('material', 'Material'), ('task', 'Offene Aufgabe'), ('safety', 'Sicherheit/Mangel')], max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Wichtig'), ('urgent', 'Dringend')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('done', 'Erledigt')], default='open', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('details', models.TextField(max_length=3000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_handovers', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='core.station')),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correction_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='core.coffeeentry')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_coffee_entries', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coffee_entries', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coffee_entries', to='core.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=1500)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.station')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='BirthdayPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_preferences', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthdays', to='core.station')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True, max_length=1500)),
                ('url', models.URLField(blank=True, max_length=600)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.feedsource')),
            ],
            options={
                'ordering': ['-published_at', '-imported_at'],
                'indexes': [models.Index(fields=['source', '-published_at'], name='core_feedit_source__5ddf69_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_feed_item')],
            },
        ),
        migrations.CreateModel(
            name='HandoverRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.handoverentry')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('handover', 'version'), name='unique_handover_version')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Mitglied'), ('shift_lead', 'Schichtleitung'), ('cashier', 'Kassenwart'), ('admin', 'Admin'), ('auditor', 'Auditor')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_memberships', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.station')),
            ],
            options={
                'ordering': ['station', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'station'), name='unique_station_membership')],
            },
        ),
        migrations.AddIndex(
            model_name='handoverentry',
            index=models.Index(fields=['station', 'status', '-created_at'], name='core_handov_station_af30c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='coffeeentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents', 0), _negated=True), name='coffee_amount_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='birthdaypreference',
            constraint=models.UniqueConstraint(fields=('user', 'station'), name='unique_station_birthday'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['station', '-created_at'], name='core_audite_station_6a9f5a_idx'),
        ),
    ]
