# Generated by Django 5.2.16 on 2026-07-28 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coffeeentry',
            constraint=models.UniqueConstraint(condition=models.Q(('correction_of__isnull', False)), fields=('correction_of',), name='unique_coffee_correction'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_membership'),
        ),
    ]
